#服务端口号
server:
  port: 7701

#注册中心配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7900/eureka
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

#微服务配置
spring:
  application:
    name: springcloud-provider2