#
# 版权所有：大千连和（深圳）网络科技有限公司 2018
#   描述: 微服务注册中心配置文件
#
#   注意：
#
#   修改记录：
#   修改人    日期          修改内容
#   ------------------------------------------------------------
#   yuantli  2018/05/26 -  创建
#
#

#设置注册中心端口号
server:
  port: 7900

#配置注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7900/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

#配置注册中心微服务名
spring:
  application:
    name: dqcloud-servicecenter

  datasource:
      platform: mysql
      url: jdbc:mysql://111.230.170.178:3306/alicerp?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
      username: root
      password: jingyupaopao666!
      driver-class-name: com.mysql.jdbc.Driver
