#设置服务端口
server:
  port: 7800

#设置注册中心信息
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7900/eureka/

#设置服务名
spring:
  application:
    name: springcloud-consumer

#启用熔断器
feign:
  hystrix:
    enabled: true