#服务端口号
server:
  port: 7700

#注册中心配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7900/eureka
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

#微服务配置
spring:
  application:
    name: springcloud-provider
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    platform: mysql
    url: jdbc:mysql://111.230.170.178:3306/alicerp?userUnicode=true&characterEncoding=utf-8
    username: root
    password: jingyupaopao666
    driver-class-name: com.mysql.jdbc.Driver